---
apiVersion: v1
kind: Service
metadata:
  name: product-catalogue
  labels:
    app: product-catalogue
spec:
  type: NodePort
  selector:
    app: product-catalogue
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalogue
spec:
  selector:
    matchLabels:
      app: product-catalogue
  replicas: 3
  template:
    metadata:
      labels:
        app: product-catalogue
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
      - name: product-catalogue
        image: 10.0.1.9:8082/product-catalogue:3
        ports:
        - containerPort: 8020
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1