---
apiVersion: v1
kind: Service
metadata:
  name: stock-manager
  labels:
    app: stock-manager
spec:
  type: NodePort
  selector:
    app: stock-manager
  ports:
  - protocol: TCP
    port: 8030
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-manager
spec:
  spec:
  selector:
    matchLabels:
      app: stock-manager
  replicas: 3
  template:
    metadata:
      labels:
        app: stock-manager
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: stock-manager
        image: 10.0.1.9:8082/stock-manager:latest
        ports:
        - containerPort: 8030
        livenessProbe:
          httpGet:
            path: /health
            port: 8030
          initialDelaySeconds: 30
          timeoutSeconds: 1